/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Complain extends Bills {

    public String complain ;
    Email eml = new Email();

    public Complain() {
        initComponents();
        this.setLocationRelativeTo(null);
        meter_id1.setText(umeter_id);          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        complain_text = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        meter_id1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bill_id1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Complain");
        setMinimumSize(new java.awt.Dimension(673, 506));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter your complain :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 80, 160, 20);

        complain_text.setColumns(20);
        complain_text.setRows(5);
        jScrollPane1.setViewportView(complain_text);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 120, 360, 220);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 360, 72, 27);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Meter ID : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 20, 90, 30);

        meter_id1.setEditable(false);
        meter_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meter_id1ActionPerformed(evt);
            }
        });
        getContentPane().add(meter_id1);
        meter_id1.setBounds(140, 20, 130, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Bill ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 20, 90, 30);

        bill_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_id1ActionPerformed(evt);
            }
        });
        getContentPane().add(bill_id1);
        bill_id1.setBounds(390, 20, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricitybillingsystem/filo copyrr.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-3, -4, 670, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Submit
         Complain cmp = new Complain();
         cmp.meter_id = meter_id1.getText();
         cmp.bill_id = bill_id1.getText();
         cmp.complain = complain_text.getText();

        try {
            eml.sendEmail3(cmp);
            JOptionPane.showMessageDialog(null, "Your Complain has been submitted successfully", "Done",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
                
            } catch (Exception ex) {
                Logger.getLogger(PayBills.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void meter_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meter_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meter_id1ActionPerformed

    private void bill_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_id1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Complain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bill_id1;
    private javax.swing.JTextArea complain_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField meter_id1;
    // End of variables declaration//GEN-END:variables
}
