package electricitybillingsystem;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.lang.String;
import java.awt.Image;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.*;
import javax.swing.JPasswordField;
/**
 *
 * @author feloa
 */

public class newCustomer extends javax.swing.JFrame {
byte[] image;
String imagepath="";
ImageIcon myimage;
    /**
     * Creates new form newCustomer
     */
    public newCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }public ImageIcon seticon(String myimage,byte[] image){
        if(myimage!=null){  
         this.myimage = new ImageIcon(myimage);
        }else{
            this.myimage=new ImageIcon(image);}
        Image img1= this.myimage.getImage();
        Image img2=img1.getScaledInstance(cus_Photo.getWidth(), cus_Photo.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i=new ImageIcon(img2);
        return i;
    }
    boolean  isNumeric(String strNum){
if (strNum==null){
return false;}
try{
    double d = Double.parseDouble(strNum);


}catch (NumberFormatException nfe){

    return false;

}

return true;


}    
    public static boolean containsNumbers(String string) {
        if (string == null || string.isEmpty()) {
            return false;
        }
        for (int i = 0; i < string.length(); ++i) {
            if (Character.isDigit(string.charAt(i))) {
                return true;
            }
        }
        return false;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cus_SignUp = new javax.swing.JButton();
        cus_Name = new javax.swing.JTextField();
        cus_Address = new javax.swing.JTextField();
        cus_Email = new javax.swing.JTextField();
        cus_Number = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cus_UserName = new javax.swing.JTextField();
        cus_Upload = new javax.swing.JButton();
        cus_Photo = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cus_Region = new javax.swing.JComboBox<>();
        cus_PassWord = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cus_PassWord2 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(819, 680));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(833, 642));
        jPanel1.setPreferredSize(new java.awt.Dimension(833, 642));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Customer Sign Up");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 10, 206, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 60, 60, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 100, 54, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Region");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 130, 70, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 180, 50, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Mobile Number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(140, 220, 106, 20);

        cus_SignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cus_SignUp.setText("Sign Up");
        cus_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_SignUpActionPerformed(evt);
            }
        });
        jPanel1.add(cus_SignUp);
        cus_SignUp.setBounds(690, 570, 100, 50);
        jPanel1.add(cus_Name);
        cus_Name.setBounds(280, 60, 250, 22);

        cus_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_AddressActionPerformed(evt);
            }
        });
        jPanel1.add(cus_Address);
        cus_Address.setBounds(280, 100, 250, 22);
        jPanel1.add(cus_Email);
        cus_Email.setBounds(280, 180, 250, 22);
        jPanel1.add(cus_Number);
        cus_Number.setBounds(280, 220, 250, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("UserName");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(160, 260, 70, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("PassWord");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(160, 300, 67, 20);
        jPanel1.add(cus_UserName);
        cus_UserName.setBounds(280, 260, 250, 22);

        cus_Upload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cus_Upload.setText("Choose file");
        cus_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_UploadActionPerformed(evt);
            }
        });
        jPanel1.add(cus_Upload);
        cus_Upload.setBounds(110, 470, 130, 50);

        cus_Photo.setBackground(new java.awt.Color(255, 255, 255));
        cus_Photo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 0, 102)));
        jPanel1.add(cus_Photo);
        cus_Photo.setBounds(280, 380, 250, 232);

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(580, 570, 100, 50);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Upload The Contract");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 440, 150, 20);

        cus_Region.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cus_Region.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giza", "Maadi", "Dokky", "Ainshams", "Helwan" }));
        jPanel1.add(cus_Region);
        cus_Region.setBounds(280, 140, 250, 22);
        jPanel1.add(cus_PassWord);
        cus_PassWord.setBounds(280, 300, 250, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Confirm PassWord");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 340, 140, 20);

        cus_PassWord2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_PassWord2ActionPerformed(evt);
            }
        });
        jPanel1.add(cus_PassWord2);
        cus_PassWord2.setBounds(280, 340, 250, 22);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricitybillingsystem/filo copyrr.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 820, 660);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//  void Validate(Customer_N cus1) {
//      
//        if(cus1.name.length()<10 ||containsNumbers(cus_Name.getText()) ){
//                    JOptionPane.showMessageDialog(null, " name must be atleast 10 characters and cant contain digits!");
//                }
//                else if(cus1.address.equals("")){
//                    JOptionPane.showMessageDialog(null, " Address required!");
//                }
//
//                else if(!cus1.email.contains("@")|| !cus1.email.contains(".com")){
//                    JOptionPane.showMessageDialog(null, "Invalid Email!");
//                }
//                else if(  cus1.mobileNumber.length()!=11 || !isNumeric(cus_Number.getText())){
//                    JOptionPane.showMessageDialog(null, "invalid MobileNumber!");
//                }
//                 
//              else  if(cus1.userName.equals("") || cus1.userName.length()<8){
//                    JOptionPane.showMessageDialog(null, "UserName must be 8 characters or more!");
//                }
//                else if( cus1.passWord.equals("")|| cus1.passWord.length()<8){
//                    JOptionPane.showMessageDialog(null, "password must be atleast 8 characters or more!");
//                }
//                else if(!cus1.passWord.equals(cus1.passWord2)){
//                JOptionPane.showMessageDialog(null, "password doesnt match!");
//                }
//                
//                 else if(cus1.contract==null){
//                    JOptionPane.showMessageDialog(null, "contract required!");
//                    
//                }
//                else {JOptionPane.showMessageDialog(null, "your meter ID is: " );
//                
//                cus_Name.setText(null);
//              cus_Address.setText(null);
//              cus_Email.setText(null);
//              cus_Number.setText(null);
//              cus_UserName.setText(null);
//              cus_PassWord.setText(null);
//              cus_Photo.setIcon(null);
//               cus_PassWord2.setText(null);
//
//                 }
//        
//              // code to be executed
//  }
    


 

    private void cus_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_SignUpActionPerformed
           
        
        
           Customers cus1 = new Customers();
           
           cus1.name = cus_Name.getText();
           cus1.address = cus_Address.getText();
           cus1.region = (String) cus_Region.getSelectedItem();
           cus1.email = cus_Email.getText();
           cus1.mobile = cus_Number.getText();
           cus1.username = cus_UserName.getText();
           cus1.password = cus_PassWord.getText();
           cus1.contract = cus_Photo.getIcon();
           cus1.password2 = cus_PassWord2.getText();
           
           if(cus1.Validate(cus1)==1){
               try {
                   if(cus1.register(cus1)==1){
                       cus_Name.setText(null);
                       cus_Address.setText(null);
                       cus_Email.setText(null);
                       cus_Number.setText(null);
                       cus_UserName.setText(null);
                       cus_PassWord.setText(null);
                       cus_Photo.setIcon(null);
                       cus_PassWord2.setText(null);
                   }} catch (Exception ex) {
                   Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
           
           
         
                
// TODO add your handling code here:
    }//GEN-LAST:event_cus_SignUpActionPerformed

    private void cus_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cus_AddressActionPerformed

    private void cus_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_UploadActionPerformed
        JFileChooser file = new JFileChooser();      
        file.setCurrentDirectory(new File("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("all pic","png","jpg","jpeg","gif");
        file.addChoosableFileFilter(filter);
        int a = file.showSaveDialog(null);
        if(a==JFileChooser.APPROVE_OPTION){
            File f=file.getSelectedFile();
            String p=f.getAbsolutePath();
        cus_Photo.setIcon(seticon(p,null));
        }

// TODO add your handling code here:
    }//GEN-LAST:event_cus_UploadActionPerformed

    private void cus_PassWord2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_PassWord2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cus_PassWord2ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }
//        new LoginForm().setVisible(true);    }                                          
//        new LoginForm().setVisible(true);        new LoginForm().setVisible(true);    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField cus_Address;
    private javax.swing.JTextField cus_Email;
    private javax.swing.JTextField cus_Name;
    private javax.swing.JTextField cus_Number;
    private javax.swing.JPasswordField cus_PassWord;
    private javax.swing.JPasswordField cus_PassWord2;
    private javax.swing.JLabel cus_Photo;
    private javax.swing.JComboBox<String> cus_Region;
    private javax.swing.JButton cus_SignUp;
    private javax.swing.JButton cus_Upload;
    private javax.swing.JTextField cus_UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
