package electricitybillingsystem;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */





/**
 *
 * @author Kerolos
 */

import java.text.*;
import java.awt.print.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;



import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class printBill_form extends printBill {

    /**
     * Creates new form NewJFrame
     */
    public printBill_form() {
        initComponents();
        this.setLocationRelativeTo(null);
        createConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        meter_id_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Print Bill");
        setMinimumSize(new java.awt.Dimension(780, 505));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(500, 30, 262, 400);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 390, 71, 23);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(384, 390, 90, 23);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Month", "Year", "Meter ID", "Consumption", "Total"
            }
        )
        {
            public boolean isCellEditable(int row ,int column){
                return false ;
            }
        }

    );
    table1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            table1MouseEntered(evt);
        }
    });
    jScrollPane3.setViewportView(table1);

    getContentPane().add(jScrollPane3);
    jScrollPane3.setBounds(10, 130, 474, 248);

    meter_id_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    meter_id_text.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            meter_id_textActionPerformed(evt);
        }
    });
    getContentPane().add(meter_id_text);
    meter_id_text.setBounds(121, 46, 165, 22);

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel4.setText("Meter ID");
    getContentPane().add(jLabel4);
    jLabel4.setBounds(56, 49, 59, 16);

    jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButton3.setText("View");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton3);
    jButton3.setBounds(308, 46, 72, 23);

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricitybillingsystem/filo copy 2rr.jpg"))); // NOI18N
    jLabel1.setText("jLabel1");
    getContentPane().add(jLabel1);
    jLabel1.setBounds(0, 0, 780, 510);

    pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Show Button 
        printBill bill= new printBill();
        
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
//        model.setRowCount(0);
        int row = table1.getSelectedRow();

        bill.bill_id = (String) model.getValueAt(row,0);
        bill.month = (String) model.getValueAt(row,1);
        bill.year = (String) model.getValueAt(row,2);
        bill.meter_id = (String) model.getValueAt(row,3);
        bill.consumption = Integer.parseInt((String) model.getValueAt(row,4));
        bill.total_bill = Integer.parseInt((String) model.getValueAt(row,5));

        jTextArea1.setText(bill.setBill(bill));
       
       
       
       
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            jTextArea1.print();
        } catch (java.awt.print.PrinterException l) {
            System.err.format("Not Found",l.getMessage());
            Logger.getLogger(printBill.class.getName()).log(Level.SEVERE, null, l);
        }
        
        
        
        
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void meter_id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meter_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meter_id_textActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Bills bill1 = new Bills();
        bill1.meter_id = meter_id_text.getText() ;
        DefaultTableModel tableModel = (DefaultTableModel) table1.getModel();
        bill1.viewPrintBills(bill1,table1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void table1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printBill_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField meter_id_text;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
